{
  "openapi": "3.0.0",
  "info": {
    "title": "Municca Technical Test",
    "version": "1.0.0",
    "description": "API for user document management."
  },
  "paths": {
    "/auth": {
      "post": {
        "summary": "Authenticate user",
        "description": "Authenticate a user with email and password and return an access token.",
        "tags": ["Auth"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "john@mail.com"
                  },
                  "password": {
                    "type": "string",
                    "format": "password",
                    "minLength": 6,
                    "example": "12345678"
                  }
                },
                "required": ["email", "password"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful authentication",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string",
                  "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
              }
            }
          },
          "400": {
            "description": "Invalid credentials",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Invalid credentials"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "summary": "Create a new user",
        "description": "Register a new user by providing name, email, and password.",
        "tags": ["Users"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 3,
                    "example": "John Doe"
                  },
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                  },
                  "password": {
                    "type": "string",
                    "format": "password",
                    "minLength": 6,
                    "example": "password123"
                  }
                },
                "required": ["name", "email", "password"]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          },
          "400": {
            "description": "Bad request - Email already exists",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "E-mail already exists"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Fetch all users",
        "description": "Retrieve a list of all users.",
        "tags": ["Users"],
        "responses": {
          "200": {
            "description": "A list of users",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                },
                "example": [
                  {
                    "id": "4a6fd64d-d50e-4f53-b0c3-a9859d71e417",
                    "email": "user1@example.com",
                    "name": "John Doe",
                    "createdAt": "2024-10-01T10:00:00.000Z",
                    "updatedAt": "2024-10-01T10:00:00.000Z"
                  },
                  {
                    "id": "4a6fd64d-d50e-4f53-b0c3-a9859d71e418",
                    "email": "user2@example.com",
                    "name": "Jane Doe",
                    "createdAt": "2024-10-01T10:00:00.000Z",
                    "updatedAt": "2024-10-01T10:00:00.000Z"
                  }
                ]
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}": {
      "delete": {
        "summary": "Delete a user",
        "description": "Delete a user by their unique user ID.",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "description": "UUID of the user to be deleted",
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "4a6fd64d-d50e-4f53-b0c3-a9859d71e417"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "User successfully deleted"
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Get user by ID",
        "description": "Retrieve a single user by their ID.",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "description": "The ID of the user to retrieve",
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "4a6fd64d-d50e-4f53-b0c3-a9859d71e417"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "4a6fd64d-d50e-4f53-b0c3-a9859d71e417",
                  "email": "user@example.com",
                  "name": "John Doe",
                  "createdAt": "2024-10-01T10:00:00.000Z",
                  "updatedAt": "2024-10-01T10:00:00.000Z"
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update user by ID",
        "description": "Update the details of an existing user by their ID.",
        "tags": ["Users"],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "description": "The ID of the user to update",
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "4a6fd64d-d50e-4f53-b0c3-a9859d71e417"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              },
              "example": {
                "email": "newemail@example.com",
                "name": "New Name"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "4a6fd64d-d50e-4f53-b0c3-a9859d71e417",
                  "email": "newemail@example.com",
                  "name": "New Name",
                  "createdAt": "2024-10-01T10:00:00.000Z",
                  "updatedAt": "2024-10-01T10:10:00.000Z"
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/documents/{documentId}/approve": {
      "patch": {
        "summary": "Approve a document",
        "description": "Approve a document associated with the authenticated user.",
        "tags": ["Documents"],
        "parameters": [
          {
            "name": "documentId",
            "in": "path",
            "required": true,
            "description": "The ID of the document to approve",
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "d0fecd09-0fa9-44d5-8f58-ef3bd04d4b5b"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Document approved successfully"
          },
          "404": {
            "description": "User or document not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/documents/{documentId}/reject": {
      "patch": {
        "summary": "Reject a user's document",
        "description": "Rejects a specific document associated with the authenticated user by document ID.",
        "tags": ["Documents"],
        "parameters": [
          {
            "name": "documentId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "description": "The UUID of the document to reject."
          }
        ],
        "responses": {
          "204": {
            "description": "Document rejected successfully"
          },
          "404": {
            "description": "User or document not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/documents": {
      "post": {
        "summary": "Create a new document",
        "description": "Creates a new document for the authenticated user.",
        "tags": ["Documents"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 3,
                    "example": "My Document"
                  }
                },
                "required": ["name"]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Document created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "format": "uuid",
                      "example": "d0fecd09-0fa9-44d5-8f58-ef3bd04d4b5b"
                    },
                    "name": {
                      "type": "string",
                      "example": "My Document"
                    },
                    "userId": {
                      "type": "string",
                      "format": "uuid",
                      "example": "f4aebdc2-5c28-4d7e-a964-6c8f27d8c2f9"
                    },
                    "createdAt": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2024-10-06T10:00:00Z"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid request body",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Validation error"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "get": {
        "summary": "Fetch user's documents",
        "description": "Retrieves a list of documents associated with the authenticated user.",
        "tags": ["Documents"],
        "responses": {
          "200": {
            "description": "List of documents retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string",
                        "format": "uuid",
                        "example": "d0fecd09-0fa9-44d5-8f58-ef3bd04d4b5b"
                      },
                      "name": {
                        "type": "string",
                        "example": "Document Name"
                      },
                      "userId": {
                        "type": "string",
                        "format": "uuid",
                        "example": "a4d5e1d8-0fa9-44d5-8f58-ef3bd04d4b5b"
                      },
                      "status": {
                        "type": "string",
                        "example": "PENDING"
                      },
                      "createdAt": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2023-01-01T12:00:00Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/documents/{documentId}": {
      "delete": {
        "summary": "Delete a user's document",
        "description": "Deletes a specific document associated with the authenticated user.",
        "tags": ["Documents"],
        "parameters": [
          {
            "name": "documentId",
            "in": "path",
            "required": true,
            "description": "The ID of the document to be deleted.",
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "d0fecd09-0fa9-44d5-8f58-ef3bd04d4b5b"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Document deleted successfully"
          },
          "404": {
            "description": "User or document not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "get": {
        "summary": "Get user's document by ID",
        "description": "Retrieves a specific document associated with the authenticated user by document ID.",
        "tags": ["Documents"],
        "parameters": [
          {
            "name": "documentId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "description": "The UUID of the document to retrieve."
          }
        ],
        "responses": {
          "200": {
            "description": "Document retrieved successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "format": "uuid",
                      "example": "d0fecd09-0fa9-44d5-8f58-ef3bd04d4b5b"
                    },
                    "name": {
                      "type": "string",
                      "example": "Document Name"
                    },
                    "userId": {
                      "type": "string",
                      "format": "uuid",
                      "example": "a4d5e1d8-0fa9-44d5-8f58-ef3bd04d4b5b"
                    },
                    "status": {
                      "type": "string",
                      "example": "PENDING"
                    },
                    "createdAt": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2023-01-01T12:00:00Z"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User or document not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      },
      "put": {
        "summary": "Update a user's document",
        "description": "Updates the name of a specific document associated with the authenticated user by document ID.",
        "tags": ["Documents"],
        "parameters": [
          {
            "name": "documentId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "description": "The UUID of the document to update."
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 3,
                    "example": "Updated Document Name"
                  }
                },
                "required": ["name"]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Document updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "format": "uuid"
                    },
                    "name": {
                      "type": "string"
                    },
                    "userId": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User or document not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "User not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Something went wrong"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "user@example.com"
          },
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "id": {
            "type": "string",
            "example": "4a6fd64d-d50e-4f53-b0c3-a9859d71e417"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "example": "2024-10-01T10:00:00.000Z"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "example": "2024-10-01T10:00:00.000Z"
          }
        }
      },
      "UpdateUserRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "New Name",
            "minLength": 3
          },
          "email": {
            "type": "string",
            "example": "newemail@example.com",
            "format": "email"
          }
        }
      },
      "Document": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "example": "document-name.pdf"
          },
          "id": {
            "type": "string",
            "example": "b6fd64d-d50e-4f53-b0c3-a9859d71e421"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "example": "2024-10-01T10:00:00.000Z"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "example": "2024-10-01T10:00:00.000Z"
          },
          "status": {
            "type": "string",
            "nullable": true,
            "example": "PENDING"
          },
          "userId": {
            "type": "string",
            "example": "4a6fd64d-d50e-4f53-b0c3-a9859d71e417"
          }
        }
      }
    },
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
